spring:
  profiles:
    active: prod
    group:
      dev:
        - dev-db
        - dev-jpa
        - s3
        - oauth2
      prod:
        - prod-db
        - prod-jpa
        - s3
        - oauth2